### ISSUE TITLE
Python 2 compatibility issue

### ISSUE THREAD

**Issue by cleac** [Lex0ne/trafaret_validator#1]
Hi! 
Recently I've found out that the library currently is not compatible with Python 2.7, but in setup.py it is marked it is supported... I'm currently working with Python 2 and unfortunately can't move to newer versions at the moment.
May I add python2 support to project, or you were going to remove it's support?

**Comment by vmorkovyn** [comment]
Of course, you can add python2 support.

**Comment by vmorkovyn** [comment]
Will solve it with 0.3.7 version
