### ISSUE TITLE
A question on logic of setting/getting attributes

### ISSUE THREAD

**Issue by cleac** [Lex0ne/trafaret_validator#7]
### Problem:

According to code in the library, there is possibility to change validators after it's instantiation... Which breaks logic of library, and produces bugs. However, logic in the code does not work at all (at least with Python 2, haven't tested behavior in Python 3 yet), because we can change validators only at _instance_ level, what causes to validator break down completely. After such "mutation" it becomes fully unusable, so it is a bug.

### Possible solution:

My proposal is to remove possibility to change validator after it's creation, and replace it with possibility to mutate data passed to class using this api. In my opinion, the declarative way to implement validator means that you are not able to change it afterwards, and sometimes there should be possibility to change data _after_ validation _(it will smell not good, but at least have a bit of sense, unlike current implementation)_ :smile:.

Example of usage should be like this:
```python
class GreatValidator(TrafaretValidator):
    id = t.Int()
    name = t.String(allow_empty=False)

...

vld = GreatValidator(**json.loads(request.data))  # request.data = '{"id": 1}'
if not vld.validate():
    if 'name' in vld.errors:
        vld.name = 'Anonymous'
    if vld.validate():
        abort(412)
author = Author(id=vld.id, name=vld.name)  # <Author id=1 name="Anonymous">
```

**Comment by vmorkovyn** [comment]
You can't reassign trafaret variable, look at __setattr__:
```python
def __setattr__(self, name, value):
    if name in self._validators.keys():
        raise AttributeError('Cannot reassign validator.')
```

If you need return another value if data is not valid, you can do as in this example:
```python
def name_validator(value):
    if value is None:
        return  'Anonymous'
    return check_and_return_str(value)

class GreatValidator(TrafaretValidator):
    id = t.Int()
    name = t.Call(name_validator)
```

**Comment by cleac** [comment]
Well, after testing this thing in Python2.7 I got some strange behavior, you can check it out [here](https://gist.github.com/cleac/6e9810283636c180014f2b1c27d11e95). I presume, it's a bug :bug: 

The case of custom value looks good, so is there any sense in possibility to actually _write_ some changes to validator or it's instance?

**Comment by vmorkovyn** [comment]
Ok, I understand you. Will solve it with 0.4.0 version
